@localhost=https://localhost:5080

###

# Localhost server
GET {{localhost}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpYyIsImlzcyI6Ik5vZGVBcGlBdXRoIiwiaWF0IjoxNjMxNzA0NjU2LCJleHAiOjE2MzE3MDgyNTYsImF1ZCI6IjYxNDBmMzlhZTE4NDE0MjQzNDg0MTJkNCJ9.EITfKK08aOSmYp-51Efasncj9q9Yldgw5LD_GYMdl7Q

###  Register Route
POST {{localhost}}/auth/register
Content-Type: application/json

{
    "email" : "Erika@gmail.com",
    "password": "123456"
}

### Login Route
POST  {{localhost}}/auth/login
Content-Type: application/json

{
    "email" : "Erika@gmail.com",
    "password": "123456"
}

### Refresh Token Route
POST {{localhost}}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpYyIsImlzcyI6Ik5vZGVBcGlBdXRoIiwiaWF0IjoxNjMxNjQ1MDY3LCJleHAiOjE2NjMyMDI2NjcsImF1ZCI6IjYxNDBjOTdlZTQ1NmU1MjMzMmE4Nzg0MCJ9.RvNXu5JQE8rngJdKYPwKbEu2zwK0SDTqNY2Ko1xmLhI"
}

### Logout Route
DELETE {{localhost}}/auth/logout