@localhost=https://localhost:5080

###

# Localhost server
GET {{localhost}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpYyIsImlzcyI6Ik5vZGVBcGlBdXRoIiwiaWF0IjoxNjMxNzA0NjU2LCJleHAiOjE2MzE3MDgyNTYsImF1ZCI6IjYxNDBmMzlhZTE4NDE0MjQzNDg0MTJkNCJ9.EITfKK08aOSmYp-51Efasncj9q9Yldgw5LD_GYMdl7Q

###  Register Route
POST {{localhost}}/auth/register
Content-Type: application/json

{
    "email" : "Erika@gmail.com",
    "password": "123456"
}

### Login Route
POST  {{localhost}}/auth/login
Content-Type: application/json

{
    "email" : "Erika@gmail.com",
    "password": "123456"
}

### Refresh Token Route
POST {{localhost}}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpYyIsImlzcyI6Ik5vZGVBcGlBdXRoIiwiaWF0IjoxNjMyMDc2Mjg1LCJleHAiOjE2NjM2MzM4ODUsImF1ZCI6IjYxNDBmMzlhZTE4NDE0MjQzNDg0MTJkNCJ9.jLUtemwMhxXH_I856uhVYkBosAg_dketojEhaM5cpTA"
}

### Logout Route
DELETE {{localhost}}/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpYyIsImlzcyI6Ik5vZGVBcGlBdXRoIiwiaWF0IjoxNjMyMDc2MzUzLCJleHAiOjE2NjM2MzM5NTMsImF1ZCI6IjYxNDBmMzlhZTE4NDE0MjQzNDg0MTJkNCJ9.UdTmfx0ZD_qqWrvcHxmty2qkjbyoIMc5GBWfK-3vGKA"
}